gui:
  # The number of lines you scroll by when scrolling the main window
  scrollHeight: 10
os:
  editPreset: 'emacs'
customCommands:
  - key: 'o'
    context: 'files'
    command: '{{ .Form.OpenInApp }} {{ .SelectedFile.Name | quote }}'
    description: 'Open In'
    prompts:
      - type: 'menu'
        title: 'Open In...'
        key: 'OpenInApp'
        options:
          - value: 'idea'
            name: 'IntelliJ'
            description: 'IntelliJ'
          - value: 'rider64'
            name: 'Rider'
            description: 'Rider'
          - value: 'emacsclientw -n'
            name: 'Emacs'
            description: 'Emacs'
