; Generated by AutoGUI 2.5.7
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

LastFocused := Winget, A

GetTitles(prefix, executable)
{
    out := []
    Winget, hWnds, List, ahk_exe %executable%
    Loop, % hWnds {
        hWnd := hWnds%A_Index%
        WinGetTitle, wTitle, ahk_id %hWnd%
        out.Push([prefix, wTitle, hWnd])
    }
    
    return out
}

ArrConcat(a1, a2) {
    out := []
    for index in a1 {
        out.Push(a1[a_index])
    }
    for index in a2 {
        out.Push(a2[a_index])
    }
    return out
}

GetAllTitles() {
    Windows := GetTitles("Emacs", "emacs.exe")
    Windows := ArrConcat(Windows, GetTitles("Rider", "rider64.exe"))
    Windows := ArrConcat(Windows, GetTitles("IntelliJ", "idea64.exe"))
    return Windows
}

Windows := GetAllTitles()

for index in Windows {
    prefix := Windows[a_index][1]
    title := Windows[a_index][2]
    hWnd := Windows[a_index][3]

    offset := 16 + (index - 1) * 32

    Gui Add, Text, x112 y%offset% w422 h23 +0x200, %prefix%: %title%
}

Gui Add, Button, x16 y16 w80 h23, &A
Gui Add, Button, x16 y48 w80 h23, &S
Gui Add, Button, x16 y80 w80 h23, &D
Gui Add, Button, x16 y112 w80 h23, &D

Gui Add, Button, x16 y160 w80 h23, &H
Gui Add, Button, x16 y192 w80 h23, &J
Gui Add, Button, x16 y224 w80 h23, &K
Gui Add, Button, x16 y256 w80 h23, &L

Gui Show, w620 h420, IDE Switcher

; OnMessage(0x08, "WM_KILLFOCUS")
; WM_KILLFOCUS() {
;     ExitApp
; }

ShowAndExit(hWnd) {
	WinGetTitle, Title, A
    WinActivate, ahk_id %hWnd%
    ExitApp
    return
}

a::ShowAndExit(Windows[1][3])
s::ShowAndExit(Windows[2][3])
d::ShowAndExit(Windows[3][3])
f::ShowAndExit(Windows[4][3])

h::ShowAndExit(Windows[5][3])
j::ShowAndExit(Windows[6][3])
k::ShowAndExit(Windows[7][3])
l::ShowAndExit(Windows[8][3])

Return

GuiEscape:
GuiClose:
    Gui, Destroy
